spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/casbin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  type-handlers-package: indi.mat.work.project.handler


logging:
  charset:
    console: UTF-8
  level:
    # 404 后台报错， 浏览器访问或者 Accept: text/html 请求结果，未找到时，后台Exception，不影响运行，但是会影响日志手机， 关闭 ConainerBase解决
    org.apache.catalina.core.ContainerBase: off
    indi.mat: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework: info
    root: info
  switch: spring

debug: true


